### ISSUE TITLE
Does it work with artillery-plugin-expect?

### ISSUE THREAD

**Issue by mstn** [orchestrated-io/artillery-engine-lambda#3]
Hi, thanks for this project. I am just wondering if it works with  [artillery-plugin-expect](https://github.com/artilleryio/artillery-plugin-expect).

**Comment by wzedi** [comment]
No - this engine has not been tested with expect. If you have time please submit a PR. Otherwise we'll look at this as soon as we can.

**Comment by mstn** [comment]
Hi. I started to work on a pr https://github.com/orchestrated-io/artillery-engine-lambda/pull/4. In theory, it should be enough to make it work with https://github.com/artilleryio/artillery-plugin-expect, but I am not sure. I will work on that soon.

**Comment by mstn** [comment]
Apparently, the plugin assumes http requests (e.g. with an url). I'll see what I can do without being too hacky. If you have any suggestion, you are welcome!

**Comment by mstn** [comment]
@wzedi done. I tested it with `artillery-plugin-expect`, too.

**Comment by mstn** [comment]
Closing since it was addressed in https://github.com/orchestrated-io/artillery-engine-lambda/pull/4
